version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Set these in .env file (not committed to git)
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  # Optional: Local MySQL for development
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-murach}
      MYSQL_USER: ${MYSQL_USER:-murach_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-sesame}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql_scripts:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
